# Systemd environment file for the otelcol-middleware-gpu service

# Command-line options for the otelcol-middleware-gpu service.
# Run `/usr/bin/otelcol-middleware-gpu --help` to see all available options.
OTELCOL_OPTIONS="--config=/etc/otelcol-middleware-gpu/config.yaml"
