# Publish helpers for pushing the Middleware GPU collector image to GHCR.
#
# This file is NOT generated by distrogen, so it survives regeneration.
# Assumes your shell is ALREADY logged in to ghcr.io (docker login done
# beforehand), so no token handling happens here.
#
# Usage (run from the middleware-gpu-collector directory):
#   make -f Makefile -f publish.mk publish VERSION=0.1.0
#
# Uses Dockerfile.build, which compiles the collector inside the image
# (build context is the project root, "..") so the host does not need a
# prebuilt binary and the binary path always matches the Dockerfile.

GHCR_REGISTRY = ghcr.io/middleware-labs
DOCKER_REPO   = $(GHCR_REGISTRY)
GHCR_IMAGE    = $(DOCKER_REPO)/$(COLLECTOR_BINARY_NAME):$(VERSION)

.PHONY: publish
publish:
ifndef VERSION
	$(error VERSION is not set. Run: make -f Makefile -f publish.mk publish VERSION=0.1.0)
endif
	docker build -f Dockerfile.build -t $(GHCR_IMAGE) --push ..
	@echo "Pushed $(GHCR_IMAGE)"
